; TrainingFeedback Windows installer.
; The PyInstaller directory is the application payload. The installer owns only
; the program directory; the application's locator and selected data root are
; deliberately outside it.

#ifndef AppVersion
  #define AppVersion "0.0.0-dev"
#endif
#ifndef SourceDir
  #define SourceDir "..\dist\TrainingFeedback"
#endif
#ifndef OutputDir
  #define OutputDir "..\dist\installer"
#endif

#define MyAppName "TrainingFeedback"
#define MyAppPublisher "TrainingFeedback"
#define MyAppExeName "TrainingFeedback.exe"
[Setup]
AppId={{A5D9D2A7-9C93-4F13-9F1A-7C1C2E1D8D60}
AppName={#MyAppName}
AppVersion={#AppVersion}
AppVerName={#MyAppName} {#AppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={code:GetDefaultProgramDirectory}
DisableDirPage=no
; Reuse only the directory checked by our helper, not Inno's unchecked history.
UsePreviousAppDir=no
AlwaysShowDirOnReadyPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir={#OutputDir}
OutputBaseFilename=TrainingFeedback-{#AppVersion}-Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=..\icon\TrainingFeedback.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
CloseApplications=yes
RestartApplications=no
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
SetupLogging=yes
VersionInfoVersion={#AppVersion}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
; Extract a complete, temporary copy for preflight before writing the target.
Source: "{#SourceDir}\*"; DestDir: "{tmp}\helper"; Flags: dontcopy recursesubdirs createallsubdirs
; Install the complete onedir payload, including _internal and bundled Qt
; resources. A single EXE is not a valid payload for this PyInstaller build.
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[UninstallDelete]
; Only the fixed receipt generated by this installation; never locator or roots.
Type: files; Name: "{app}\.training-feedback-install.json"

[Icons]
Name: "{group}\TrainingFeedback"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{autodesktop}\TrainingFeedback"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch TrainingFeedback"; Flags: nowait postinstall skipifsilent

[Code]
var
  HelperReady: Boolean;
  HelperSequence: Integer;
  PreviousDirectory: String;
  PreviousUninstaller: String;
  PreferredProgramDirectory: String;
  DeleteDataRequested: Boolean;
  CleanupOfferFile: String;
  CleanupRoot: String;

function RunHelper(Operation, Directory, Extra: String): String;
var
  ResultCode, Index: Integer;
  ResultFile, Parameters: String;
  MessageLines: TArrayOfString;
begin
  Result := '';
  if not HelperReady then
  begin
    ExtractTemporaryFiles('{tmp}\helper\*');
    HelperReady := True;
  end;
  HelperSequence := HelperSequence + 1;
  ResultFile := ExpandConstant('{tmp}\helper-result-') + IntToStr(HelperSequence) + '.txt';
  Parameters := '--installer-helper ' + Operation + ' --directory ' +
    AddQuotes(RemoveBackslashUnlessRoot(Directory)) + ' --result ' + AddQuotes(ResultFile) + Extra;
  if not Exec(ExpandConstant('{tmp}\helper\{#MyAppExeName}'), Parameters,
    ExpandConstant('{tmp}\helper'), SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    Result := 'Cannot start the installation safety helper. No installation is permitted.';
    Exit;
  end;
  if not LoadStringsFromFile(ResultFile, MessageLines) or (GetArrayLength(MessageLines) = 0) then
  begin
    Result := 'The installation safety helper did not return a result.';
    Exit;
  end;
  if ResultCode <> 0 then
  begin
    Result := MessageLines[0];
    for Index := 1 to GetArrayLength(MessageLines) - 1 do
      Result := Result + #13#10 + MessageLines[Index];
  end;
end;

function RunCleanupHelper(Operation: String; var Lines: TArrayOfString): Boolean;
var
  ResultFile, Parameters: String;
  ResultCode: Integer;
begin
  HelperSequence := HelperSequence + 1;
  ResultFile := ExpandConstant('{tmp}\cleanup-result-') + IntToStr(HelperSequence) + '.txt';
  Parameters := '--uninstall-helper ' + Operation + ' --offer ' + AddQuotes(CleanupOfferFile) +
    ' --result ' + AddQuotes(ResultFile);
  if Operation = 'commit' then Parameters := Parameters + ' --confirmed';
  Result := Exec(ExpandConstant('{app}\{#MyAppExeName}'), Parameters,
    ExpandConstant('{app}'), SW_HIDE, ewWaitUntilTerminated, ResultCode);
  if Result then
    Result := LoadStringsFromFile(ResultFile, Lines) and (GetArrayLength(Lines) >= 2);
  if Result then
    if (ResultCode <> 0) and ((Lines[0] = 'complete') or (Lines[0] = 'READY')) then
      Result := False;
  if not Result then
  begin
    SetArrayLength(Lines, 2);
    Lines[0] := 'REFUSED';
    Lines[1] := 'The cleanup helper could not complete. Retain data.';
  end;
end;

function KeepDataParameter(): Boolean;
var
  Index: Integer;
begin
  Result := False;
  for Index := 1 to ParamCount do
    if CompareText(ParamStr(Index), '/KEEPDATA') = 0 then Result := True;
end;

function CleanupReasonText(Reason: String): String;
begin
  if Reason = 'Selected data does not belong to the current user.' then
    Result := '数据目录或配置文件的 Windows 所有者与当前账号不一致（例如属于管理员组）。' +
      '' + #13#10 + '为避免删除归属不明确的数据，本次只能卸载程序并保留数据。' +
      '' + #13#10 + '本次保留这些数据，不会取得所有权或修改目录权限。'
  else if Reason = 'A selected file is in use or access is denied.' then
    Result := '数据文件正在使用，或当前账号没有所需权限。请关闭程序后重试；本次可以仅卸载程序并保留数据。'
  else if Pos('requires the Windows safety backend', Reason) > 0 then
    Result := '当前环境不支持安全删除数据，本次可以仅卸载程序并保留数据。'
  else
    Result := '安全检查未通过，本次保留数据。检查详情：' + #13#10 + Reason;
end;

function InitializeUninstall(): Boolean;
var
  Lines: TArrayOfString;
  Ready: Boolean;
  Summary, Detail, Information: String;
  Choice: Integer;
begin
  DeleteDataRequested := False;
  Result := True;
  if UninstallSilent or KeepDataParameter then Exit;
  CleanupOfferFile := ExpandConstant('{tmp}\cleanup-offer.json');
  RunCleanupHelper('probe', Lines);
  Ready := (Lines[0] = 'READY') and (GetArrayLength(Lines) >= 4);
  // Use Inno's supported task dialog layout, not manually sized forms/controls.
  // It accepts button types only, not MsgBox's MB_DEFBUTTON flags.
  if not Ready then
  begin
    Information := '当前不能删除数据。点击“仅卸载程序”会移除程序并保留数据；点击“取消”不进行卸载。' +
      '' + #13#10#13#10 + CleanupReasonText(Lines[1]);
    Result := TaskDialogMsgBox('卸载 TrainingFeedback', Information, mbInformation,
      MB_OKCANCEL, ['仅卸载程序', '取消'], 0) = IDOK;
    Exit;
  end;
  CleanupRoot := Lines[1];
  Summary := Lines[2];
  StringChangeEx(Summary, 'Files:', '文件数：', True);
  StringChangeEx(Summary, 'bytes:', '字节数：', True);
  if Lines[3] = 'Retry interrupted cleanup.' then
    Detail := '这是上次中断的清理；再次确认后仅继续清理已经核对的剩余文件。'
  else
    Detail := '范围包括此数据目录内的数据库和全部文件。';
  Information := '默认保留训练数据。请选择卸载方式，或点击“取消”。' +
    '' + #13#10#13#10 + '当前数据目录：' + #13#10 + CleanupRoot + #13#10 + Summary +
    '' + #13#10 + Detail + #13#10#13#10 +
    '只有明确选择永久删除并再次确认，才会删除此目录内的全部文件，包括图片、备份和导出。' +
    '其它数据目录和目录外备份保留；删除无法撤销。';
  Choice := TaskDialogMsgBox('卸载 TrainingFeedback', Information, mbConfirmation,
    MB_YESNOCANCEL, ['仅卸载程序，保留数据', '同时永久删除当前数据…', '取消'], 0);
  case Choice of
    IDYES: Result := True;  // First/default choice always retains data.
    IDNO:
      begin
        DeleteDataRequested := MsgBox('是否永久删除下面这个数据目录内的全部数据？' +
          '' + #13#10#13#10 + CleanupRoot + #13#10#13#10 +
          '删除无法撤销。其它数据目录和目录外备份会保留。',
          mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES;
        Result := DeleteDataRequested;  // Rejecting deletion cancels the whole uninstall.
      end;
  else
    Result := False;  // Cancel, window close, Escape and dialog failure never delete.
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Lines: TArrayOfString;
  MessageText: String;
  Index: Integer;
begin
  // Deletion happens after the ordinary final uninstall confirmation, before payload removal.
  if (CurUninstallStep <> usUninstall) or not DeleteDataRequested then Exit;
  RunCleanupHelper('commit', Lines);
  if Lines[0] <> 'complete' then
  begin
    MessageText := '数据清理未完成。保留的路径与状态：';
    for Index := 1 to GetArrayLength(Lines) - 1 do
      MessageText := MessageText + #13#10 + Lines[Index];
    MessageText := MessageText + #13#10#13#10 +
      '是否继续仅卸载程序？选择“否”保留程序，便于稍后重试清理。';
    if MsgBox(MessageText, mbError, MB_YESNO) <> IDYES then
      RaiseException('卸载已停止。剩余数据和恢复记录均已保留。');
  end;
end;

function CheckPreviousInstallation(): String;
begin
  Result := '';
  if PreviousDirectory = '' then Exit;
  // Validate the local path and root boundaries before probing directory existence.
  Result := RunHelper('validate', PreviousDirectory, '');
  if Result <> '' then Exit;
  if not DirExists(PreviousDirectory) then
  begin
    Log('TrainingFeedback: discard missing previous program directory: ' + PreviousDirectory);
    PreviousDirectory := '';
    PreviousUninstaller := '';
    Exit;
  end;
  Result := RunHelper('validate', PreviousDirectory,
    ' --uninstaller ' + AddQuotes(PreviousUninstaller));
end;

function GetDefaultProgramDirectory(Param: String): String;
begin
  Result := PreferredProgramDirectory;
  if Result = '' then
    Result := ExpandConstant('{localappdata}\Programs\{#MyAppName}');
end;

function InitializeSetup(): Boolean;
var
  ErrorText: String;
begin
  PreviousDirectory := '';
  PreviousUninstaller := '';
  PreferredProgramDirectory := ExpandConstant('{localappdata}\Programs\{#MyAppName}');
  if not RegQueryStringValue(HKCU64,
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{A5D9D2A7-9C93-4F13-9F1A-7C1C2E1D8D60}_is1',
    'InstallLocation', PreviousDirectory) then PreviousDirectory := '';
  if not RegQueryStringValue(HKCU64,
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{A5D9D2A7-9C93-4F13-9F1A-7C1C2E1D8D60}_is1',
    'UninstallString', PreviousUninstaller) then PreviousUninstaller := '';
  PreviousDirectory := RemoveBackslashUnlessRoot(PreviousDirectory);
  PreviousUninstaller := RemoveQuotes(PreviousUninstaller);
  Log('TrainingFeedback: registered previous program directory: ' + PreviousDirectory);
  Log('TrainingFeedback: registered previous uninstaller: ' + PreviousUninstaller);
  ErrorText := CheckPreviousInstallation();
  if (ErrorText = '') and (PreviousDirectory <> '') then
    PreferredProgramDirectory := PreviousDirectory;
  if ErrorText <> '' then
    Log('TrainingFeedback: previous directory is not eligible for reuse: ' + ErrorText);
  Log('TrainingFeedback: resolved default program directory: ' + PreferredProgramDirectory);
  Result := True;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  ErrorText, Extra: String;
begin
  Result := True;
  if CurPageID <> wpSelectDir then Exit;
  // Recheck registrations removed after startup; missing programs are not relocations.
  ErrorText := CheckPreviousInstallation();
  if ErrorText <> '' then
  begin
    MsgBox(ErrorText, mbError, MB_OK);
    Result := False;
    Exit;
  end;
  Log('TrainingFeedback: selected program directory: ' + WizardDirValue);
  Extra := '';
  if PreviousDirectory <> '' then
    Extra := ' --previous-directory ' + AddQuotes(PreviousDirectory);
  ErrorText := RunHelper('validate', WizardDirValue, Extra);
  if ErrorText <> '' then
  begin
    MsgBox(ErrorText, mbError, MB_OK);
    Result := False;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
  Extra: String;
begin
  Result := CheckPreviousInstallation();
  if Result <> '' then Exit;
  Log('TrainingFeedback: preparing selected program directory: ' + WizardDirValue);
  Log('TrainingFeedback: preparing previous program directory: ' + PreviousDirectory);
  Extra := '';
  if PreviousDirectory <> '' then
    Extra := ' --previous-directory ' + AddQuotes(PreviousDirectory);
  Result := RunHelper('validate', WizardDirValue, Extra);
  if Result <> '' then Exit;
  if (PreviousDirectory <> '') and not PathSame(PreviousDirectory, WizardDirValue) then
  begin
    if not WizardSilent then
      if MsgBox('Move the program from:' + #13#10 + PreviousDirectory + #13#10 +
        'to:' + #13#10 + WizardDirValue + #13#10#13#10 +
        'The previous program and its shortcuts will be uninstalled first. Your data is retained.' + #13#10 +
        'If installation fails, reinstall the program. Continue?',
        mbConfirmation, MB_YESNO) <> IDYES then
      begin
        Result := 'Program directory change cancelled. Your data is retained.';
        Exit;
      end;
    if not Exec(PreviousUninstaller,
      '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /KEEPDATA', PreviousDirectory,
      SW_HIDE, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then
    begin
      Result := 'Previous program removal did not complete. Installation stopped; data is retained.';
      Exit;
    end;
    if FileExists(AddBackslash(PreviousDirectory) + '{#MyAppExeName}') then
    begin
      Result := 'The previous executable remains. Installation stopped; data is retained.';
      Exit;
    end;
    PreviousDirectory := '';
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ErrorText: String;
begin
  if CurStep = ssInstall then
  begin
    ErrorText := RunHelper('prepare', WizardDirValue,
      ' --payload ' + AddQuotes(ExpandConstant('{tmp}\helper')));
    if ErrorText <> '' then RaiseException(ErrorText);
  end;
  if CurStep = ssPostInstall then
  begin
    ErrorText := RunHelper('register', ExpandConstant('{app}'),
      ' --uninstaller ' + AddQuotes(ExpandConstant('{uninstallexe}')));
    if ErrorText <> '' then
      RaiseException('Installation is incomplete. ' + ErrorText);
  end;
end;
