; TrainingFeedback Windows installer.
; The PyInstaller directory is the application payload. The installer owns only
; the program directory; the application's locator and selected data root are
; deliberately outside it.

#ifndef AppVersion
  #define AppVersion "0.0.0-dev"
#endif
#ifndef SourceDir
  #define SourceDir "..\dist\TrainingFeedback"
#endif
#ifndef OutputDir
  #define OutputDir "..\dist\installer"
#endif

#define MyAppName "TrainingFeedback"
#define MyAppPublisher "TrainingFeedback"
#define MyAppExeName "TrainingFeedback.exe"
[Setup]
AppId={{A5D9D2A7-9C93-4F13-9F1A-7C1C2E1D8D60}
AppName={#MyAppName}
AppVersion={#AppVersion}
AppVerName={#MyAppName} {#AppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\Programs\{#MyAppName}
DisableDirPage=no
UsePreviousAppDir=yes
AlwaysShowDirOnReadyPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir={#OutputDir}
OutputBaseFilename=TrainingFeedback-{#AppVersion}-Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=..\icon\TrainingFeedback.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
CloseApplications=yes
RestartApplications=no
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
SetupLogging=yes
VersionInfoVersion={#AppVersion}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
; Extract a complete, temporary copy for preflight before writing the target.
Source: "{#SourceDir}\*"; DestDir: "{tmp}\helper"; Flags: dontcopy recursesubdirs createallsubdirs
; Install the complete onedir payload, including _internal and bundled Qt
; resources. A single EXE is not a valid payload for this PyInstaller build.
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[UninstallDelete]
; Only the fixed receipt generated by this installation; never locator or roots.
Type: files; Name: "{app}\.training-feedback-install.json"

[Icons]
Name: "{group}\TrainingFeedback"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{autodesktop}\TrainingFeedback"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch TrainingFeedback"; Flags: nowait postinstall skipifsilent

[Code]
var
  HelperReady: Boolean;
  HelperSequence: Integer;
  PreviousDirectory: String;
  PreviousUninstaller: String;
  DeleteDataRequested: Boolean;
  CleanupOfferFile: String;
  CleanupRoot: String;

function RunHelper(Operation, Directory, Extra: String): String;
var
  ResultCode, Index: Integer;
  ResultFile, Parameters: String;
  MessageLines: TArrayOfString;
begin
  Result := '';
  if not HelperReady then
  begin
    ExtractTemporaryFiles('{tmp}\helper\*');
    HelperReady := True;
  end;
  HelperSequence := HelperSequence + 1;
  ResultFile := ExpandConstant('{tmp}\helper-result-') + IntToStr(HelperSequence) + '.txt';
  Parameters := '--installer-helper ' + Operation + ' --directory ' +
    AddQuotes(RemoveBackslashUnlessRoot(Directory)) + ' --result ' + AddQuotes(ResultFile) + Extra;
  if not Exec(ExpandConstant('{tmp}\helper\{#MyAppExeName}'), Parameters,
    ExpandConstant('{tmp}\helper'), SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    Result := 'Cannot start the installation safety helper. No installation is permitted.';
    Exit;
  end;
  if not LoadStringsFromFile(ResultFile, MessageLines) or (GetArrayLength(MessageLines) = 0) then
  begin
    Result := 'The installation safety helper did not return a result.';
    Exit;
  end;
  if ResultCode <> 0 then
  begin
    Result := MessageLines[0];
    for Index := 1 to GetArrayLength(MessageLines) - 1 do
      Result := Result + #13#10 + MessageLines[Index];
  end;
end;

function RunCleanupHelper(Operation: String; var Lines: TArrayOfString): Boolean;
var
  ResultFile, Parameters: String;
  ResultCode: Integer;
begin
  HelperSequence := HelperSequence + 1;
  ResultFile := ExpandConstant('{tmp}\cleanup-result-') + IntToStr(HelperSequence) + '.txt';
  Parameters := '--uninstall-helper ' + Operation + ' --offer ' + AddQuotes(CleanupOfferFile) +
    ' --result ' + AddQuotes(ResultFile);
  if Operation = 'commit' then Parameters := Parameters + ' --confirmed';
  Result := Exec(ExpandConstant('{app}\{#MyAppExeName}'), Parameters,
    ExpandConstant('{app}'), SW_HIDE, ewWaitUntilTerminated, ResultCode);
  if Result then
    Result := LoadStringsFromFile(ResultFile, Lines) and (GetArrayLength(Lines) >= 2);
  if Result then
    if (ResultCode <> 0) and ((Lines[0] = 'complete') or (Lines[0] = 'READY')) then
      Result := False;
  if not Result then
  begin
    SetArrayLength(Lines, 2);
    Lines[0] := 'REFUSED';
    Lines[1] := 'The cleanup helper could not complete. Retain data.';
  end;
end;

function KeepDataParameter(): Boolean;
var
  Index: Integer;
begin
  Result := False;
  for Index := 1 to ParamCount do
    if CompareText(ParamStr(Index), '/KEEPDATA') = 0 then Result := True;
end;

function InitializeUninstall(): Boolean;
var
  Form: TSetupForm;
  Information: TNewMemo;
  DeleteChoice: TNewCheckBox;
  ContinueButton, CancelButton: TNewButton;
  Lines: TArrayOfString;
  Ready: Boolean;
begin
  DeleteDataRequested := False;
  Result := True;
  if UninstallSilent or KeepDataParameter then Exit;
  CleanupOfferFile := ExpandConstant('{tmp}\cleanup-offer.json');
  RunCleanupHelper('probe', Lines);
  Ready := (Lines[0] = 'READY') and (GetArrayLength(Lines) >= 4);
  Form := CreateCustomForm(ScaleX(600), ScaleY(330), False, False);
  try
    Form.Caption := 'TrainingFeedback uninstall';
    Information := TNewMemo.Create(Form);
    Information.Parent := Form;
    Information.SetBounds(ScaleX(16), ScaleY(16), ScaleX(568), ScaleY(220));
    Information.ReadOnly := True;
    Information.ScrollBars := ssVertical;
    Information.WordWrap := True;
    if Ready then
    begin
      CleanupRoot := Lines[1];
      Information.Text := 'Program files will be removed. Data is retained unless you explicitly choose deletion.' +
        '' + #13#10#13#10 + 'Exact current data root:' + #13#10 + CleanupRoot + #13#10 + Lines[2] +
        '' + #13#10 + Lines[3] + #13#10#13#10 +
        'Deleting data removes all root files, including pictures, backups and exports inside this root. ' +
        'Other roots and external backups are retained. This cannot be undone.';
    end else
      Information.Text := 'Data deletion is disabled. You can still uninstall the program and retain data.' +
        '' + #13#10#13#10 + Lines[1];
    DeleteChoice := TNewCheckBox.Create(Form);
    DeleteChoice.Parent := Form;
    DeleteChoice.SetBounds(ScaleX(16), ScaleY(244), ScaleX(568), ScaleY(24));
    DeleteChoice.Caption := 'Delete my data at the exact path above';
    DeleteChoice.Checked := False;
    DeleteChoice.Enabled := Ready;
    ContinueButton := TNewButton.Create(Form);
    ContinueButton.Parent := Form;
    ContinueButton.SetBounds(ScaleX(356), ScaleY(284), ScaleX(108), ScaleY(28));
    ContinueButton.Caption := 'Continue';
    ContinueButton.ModalResult := mrOk;
    ContinueButton.Default := True;
    CancelButton := TNewButton.Create(Form);
    CancelButton.Parent := Form;
    CancelButton.SetBounds(ScaleX(476), ScaleY(284), ScaleX(108), ScaleY(28));
    CancelButton.Caption := 'Cancel';
    CancelButton.ModalResult := mrCancel;
    CancelButton.Cancel := True;
    if Form.ShowModal <> mrOk then
    begin
      Result := False;
      Exit;
    end;
    if Ready and DeleteChoice.Checked then
      DeleteDataRequested := MsgBox('Permanently delete all data at this exact path?' +
        '' + #13#10#13#10 + CleanupRoot + #13#10#13#10 +
        'This cannot be undone. External backups are retained.', mbConfirmation, MB_YESNO) = IDYES;
  finally
    Form.Free;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Lines: TArrayOfString;
  MessageText: String;
  Index: Integer;
begin
  // Deletion happens after the ordinary final uninstall confirmation, before payload removal.
  if (CurUninstallStep <> usUninstall) or not DeleteDataRequested then Exit;
  RunCleanupHelper('commit', Lines);
  if Lines[0] <> 'complete' then
  begin
    MessageText := 'Data cleanup did not complete. Retained paths and state:';
    for Index := 1 to GetArrayLength(Lines) - 1 do
      MessageText := MessageText + #13#10 + Lines[Index];
    MessageText := MessageText + #13#10#13#10 +
      'Continue removing only the program? Choose No to keep the helper for retry.';
    if MsgBox(MessageText, mbError, MB_YESNO) <> IDYES then
      RaiseException('Uninstall stopped. Remaining data and recovery information are retained.');
  end;
end;

function InitializeSetup(): Boolean;
begin
  RegQueryStringValue(HKCU64,
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{A5D9D2A7-9C93-4F13-9F1A-7C1C2E1D8D60}_is1',
    'InstallLocation', PreviousDirectory);
  RegQueryStringValue(HKCU64,
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{A5D9D2A7-9C93-4F13-9F1A-7C1C2E1D8D60}_is1',
    'UninstallString', PreviousUninstaller);
  PreviousDirectory := RemoveBackslashUnlessRoot(PreviousDirectory);
  PreviousUninstaller := RemoveQuotes(PreviousUninstaller);
  Result := True;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  ErrorText, Extra: String;
begin
  Result := True;
  if CurPageID <> wpSelectDir then Exit;
  Extra := '';
  if PreviousDirectory <> '' then
    Extra := ' --previous-directory ' + AddQuotes(PreviousDirectory);
  ErrorText := RunHelper('validate', WizardDirValue, Extra);
  if ErrorText <> '' then
  begin
    MsgBox(ErrorText, mbError, MB_OK);
    Result := False;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
  Extra: String;
begin
  Extra := '';
  if PreviousDirectory <> '' then
    Extra := ' --previous-directory ' + AddQuotes(PreviousDirectory);
  Result := RunHelper('validate', WizardDirValue, Extra);
  if Result <> '' then Exit;
  if (PreviousDirectory <> '') and not PathSame(PreviousDirectory, WizardDirValue) then
  begin
    Result := RunHelper('validate', PreviousDirectory,
      ' --uninstaller ' + AddQuotes(PreviousUninstaller));
    if Result <> '' then Exit;
    if not WizardSilent then
      if MsgBox('Move the program from:' + #13#10 + PreviousDirectory + #13#10 +
        'to:' + #13#10 + WizardDirValue + #13#10#13#10 +
        'The previous program and its shortcuts will be uninstalled first. Your data is retained.' + #13#10 +
        'If installation fails, reinstall the program. Continue?',
        mbConfirmation, MB_YESNO) <> IDYES then
      begin
        Result := 'Program directory change cancelled. Your data is retained.';
        Exit;
      end;
    if not Exec(PreviousUninstaller,
      '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /KEEPDATA', PreviousDirectory,
      SW_HIDE, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then
    begin
      Result := 'Previous program removal did not complete. Installation stopped; data is retained.';
      Exit;
    end;
    if FileExists(AddBackslash(PreviousDirectory) + '{#MyAppExeName}') then
    begin
      Result := 'The previous executable remains. Installation stopped; data is retained.';
      Exit;
    end;
    PreviousDirectory := '';
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ErrorText: String;
begin
  if CurStep = ssInstall then
  begin
    ErrorText := RunHelper('prepare', WizardDirValue,
      ' --payload ' + AddQuotes(ExpandConstant('{tmp}\helper')));
    if ErrorText <> '' then RaiseException(ErrorText);
  end;
  if CurStep = ssPostInstall then
  begin
    ErrorText := RunHelper('register', ExpandConstant('{app}'),
      ' --uninstaller ' + AddQuotes(ExpandConstant('{uninstallexe}')));
    if ErrorText <> '' then
      RaiseException('Installation is incomplete. ' + ErrorText);
  end;
end;
